{{- $annotations := .Values.service.annotations }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "awx.fullname" . }}
  {{- if $annotations }}
  annotations:
    {{- range $key, $value := $annotations }}
      {{ $key }}: {{ $value | quote }}
    {{- end }}
  {{- end }}
  labels:
    app.kubernetes.io/name: {{ include "awx.name" . }}
    helm.sh/chart: {{ include "awx.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "awx.name" . }}-web
    app.kubernetes.io/instance: {{ .Release.Name }}
